development:
  adapter: mysql2
  encoding: utf8
  database: swedimport_development
  username: root
  password: root
  host: localhost
	
test:
  adapter: mysql2
  encoding: utf8
  database: swedimport_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: swedimport_production
  username: root
  password: root
  host: localhost
